/**
 * Swedish Dental Reference Prices (Referenspriser) from TLV
 * Valid from January 1, 2026
 * 
 * Source: Tandvårds- och läkemedelsverket (TLV)
 * Contains 200 treatment procedures with reference prices for general and specialist dental care
 */

export interface DentalReferencePrice {
  /** Treatment code (åtgärdsnummer) */
  code: string;
  /** Swedish treatment description */
  description: string;
  /** Reference price for general dental care (allmäntandvård) in SEK, null if not applicable */
  generalPrice: number | null;
  /** Reference price for specialist dental care (specialisttandvård) in SEK, null if not applicable */
  specialistPrice: number | null;
  /** Dental technical cost if applicable */
  dentalTechCost: number | null;
  /** Dental materials included in the calculation, if applicable */
  materials: string | null;
}

export const dentalReferencePrices: DentalReferencePrice[] = [
  {
    code: "101",
    description: "Basundersökning, utförd av tandläkare",
    generalPrice: 1100,
    specialistPrice: 1100,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "103",
    description: "Kompletterande eller akut undersökning, utförd av tandläkare",
    generalPrice: 445,
    specialistPrice: 585,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "107",
    description: "Omfattande undersökning, utförd av tandläkare",
    generalPrice: 1275,
    specialistPrice: 1970,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "108",
    description: "Utredning inklusive undersökning, utförd av tandläkare",
    generalPrice: 1895,
    specialistPrice: 2960,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "111",
    description: "Basundersökning, utförd av tandhygienist",
    generalPrice: 985,
    specialistPrice: null,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "112",
    description: "Basundersökning med fullständig parodontal undersökning, utförd av tandhygienist",
    generalPrice: 1285,
    specialistPrice: null,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "113",
    description: "Akut eller annan undersökning, utförd av tandhygienist",
    generalPrice: 535,
    specialistPrice: null,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "114",
    description: "Kompletterande parodontal undersökning eller kariesutredning, utförd av tandhygienist",
    generalPrice: 785,
    specialistPrice: null,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "115",
    description: "Konsultation specialisttandvård",
    generalPrice: null,
    specialistPrice: 1060,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "116",
    description: "Konsultation specialisttandvård, omfattande",
    generalPrice: null,
    specialistPrice: 2080,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "121",
    description: "Röntgenundersökning, en bild, eller flera bilder av en tandposition",
    generalPrice: 80,
    specialistPrice: 120,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "123",
    description: "Röntgenundersökning, helstatus",
    generalPrice: 1020,
    specialistPrice: 1595,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "124",
    description: "Panoramaröntgenundersökning",
    generalPrice: 635,
    specialistPrice: 1130,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "125",
    description: "Röntgenundersökning, extraoral",
    generalPrice: 620,
    specialistPrice: 1125,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "126",
    description: "Röntgenundersökning, omfattande",
    generalPrice: 1215,
    specialistPrice: 2075,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "127",
    description: "Röntgenundersökning, delstatus",
    generalPrice: 235,
    specialistPrice: 410,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "128",
    description: "Röntgenundersökning, större delstatus",
    generalPrice: 405,
    specialistPrice: 625,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "131",
    description: "Tomografiundersökning, en kvadrant eller tandposition 3-3",
    generalPrice: 1210,
    specialistPrice: 1555,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "132",
    description: "Tomografiundersökning, två kvadranter eller sinus",
    generalPrice: 1535,
    specialistPrice: 2080,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "133",
    description: "Tomografiundersökning, tre kvadranter eller käkleder",
    generalPrice: 1920,
    specialistPrice: 2830,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "134",
    description: "Tomografiundersökning, fyra kvadranter",
    generalPrice: 2255,
    specialistPrice: 3340,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "141",
    description: "Analoga studiemodeller för behandlingsplanering",
    generalPrice: 885,
    specialistPrice: 885,
    dentalTechCost: 586.752,
    materials: "Parslipade studiemodeller.",
  },
  {
    code: "142",
    description: "Digitala studiemodeller för behandlingsplanering",
    generalPrice: 535,
    specialistPrice: 535,
    dentalTechCost: 88.0128,
    materials: " I förekommande fall frästa eller 3-D printade studiemodeller",
  },
  {
    code: "161",
    description: "Salivsekretionsmätning",
    generalPrice: 900,
    specialistPrice: 900,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "162",
    description: "Laboratoriekostnader vid mikrobiologisk undersökning",
    generalPrice: 520,
    specialistPrice: 520,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "163",
    description: "Biopsi",
    generalPrice: 1260,
    specialistPrice: 1565,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "164",
    description: "Laboratoriekostnader vid patologanatomisk diagnostik (PAD)",
    generalPrice: 895,
    specialistPrice: 895,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "201",
    description: "Rådgivande samtal eller instruktion vid risk för munhälsorelaterade sjukdomar eller problem",
    generalPrice: 600,
    specialistPrice: 600,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "204",
    description: "Profylaxskena, per skena",
    generalPrice: 1135,
    specialistPrice: 1135,
    dentalTechCost: 741.376,
    materials: "Laboratorieframställd plastskena",
  },
  {
    code: "205",
    description: "Fluorbehandling, kortare behandlingstid",
    generalPrice: 245,
    specialistPrice: 245,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "206",
    description: "Fluorbehandling",
    generalPrice: 485,
    specialistPrice: 485,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "207",
    description: "Mekaniskt avlägsnande av supragingival tandsten",
    generalPrice: 375,
    specialistPrice: 375,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "208",
    description: "Mekaniskt avlägsnande av supragingival tandsten, omfattande",
    generalPrice: 735,
    specialistPrice: 735,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "209",
    description: "Mekaniskt avlägsnande av supragingival tandsten, särskilt tidskrävande",
    generalPrice: 1145,
    specialistPrice: 1145,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "213",
    description: "Kvalificerat rådgivande samtal för beteendemedicinsk prevention, 60 minuter eller mer",
    generalPrice: 1505,
    specialistPrice: 1505,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "214",
    description: "Kvalificerat rådgivande samtal för beteendemedicinsk prevention",
    generalPrice: 695,
    specialistPrice: 695,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "250",
    description: "Rådgivande samtal eller instruktion vid risk för munhälsorelaterade sjukdomar eller problem, distanskontakt via videolänk",
    generalPrice: 395,
    specialistPrice: 395,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "251",
    description: "Kvalificerat rådgivande samtal för sjukdoms- eller smärtprevention, 60 minuter eller mer, distanskontakt via videolänk",
    generalPrice: 1030,
    specialistPrice: 1030,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "252",
    description: "Kvalificerat rådgivande samtal för sjukdoms- eller smärtprevention, distanskontakt via videolänk",
    generalPrice: 480,
    specialistPrice: 480,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "301",
    description: "Sjukdoms- eller smärtbehandling, mindre omfattande",
    generalPrice: 450,
    specialistPrice: 590,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "302",
    description: "Sjukdoms- eller smärtbehandling",
    generalPrice: 840,
    specialistPrice: 1120,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "303",
    description: "Sjukdoms- elller smärtbehandling, omfattande",
    generalPrice: 1245,
    specialistPrice: 1665,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "304",
    description: "Sjukdoms- eller smärtbehandling, särskilt tidskrävande",
    generalPrice: 2025,
    specialistPrice: 2650,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "311",
    description: "Information eller instruktion vid munhälsorelaterade sjukdomar eller problem",
    generalPrice: 595,
    specialistPrice: 595,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "312",
    description: "Uppföljande information eller instruktion vid munhälsorelaterade sjukdomar eller problem",
    generalPrice: 240,
    specialistPrice: 240,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "313",
    description: "Beteendemedicinsk behandling, 60 minuter eller mer",
    generalPrice: 1505,
    specialistPrice: 2745,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "314",
    description: "Beteendemedicinsk behandling",
    generalPrice: 695,
    specialistPrice: 1270,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "321",
    description: "Icke-operativ behandling av kariessjukdom",
    generalPrice: 600,
    specialistPrice: 600,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "322",
    description: "Stegvis exkavering",
    generalPrice: 1350,
    specialistPrice: 1350,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "340",
    description: "Behandling av parodontal sjukdom eller periimplantit",
    generalPrice: 525,
    specialistPrice: 575,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "341",
    description: "Behandling av parodontal sjukdom eller periimplantit, omfattande",
    generalPrice: 920,
    specialistPrice: 1605,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "342",
    description: "Behandling av parodontal sjukdom eller periimplantit, tidskrävande",
    generalPrice: 1430,
    specialistPrice: 2645,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "343",
    description: "Behandling av parodontal sjukdom eller periimplantit, särskilt tidskrävande",
    generalPrice: 2165,
    specialistPrice: 4720,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "350",
    description: "Rådgivande samtal eller instruktion vid munhälsorelaterade sjukdomar eller problem, distanskontakt via videolänk",
    generalPrice: 395,
    specialistPrice: 395,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "351",
    description: "Kvalificerat rådgivande samtal vid sjukdoms- eller smärttillstånd, 60 minuter eller mer, distanskontakt via videolänk",
    generalPrice: 1030,
    specialistPrice: 1030,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "352",
    description: "Kvalificerat rådgivande samtal vid sjukdoms- eller smärttillstånd, distanskontakt via videolänk",
    generalPrice: 480,
    specialistPrice: 480,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "362",
    description: "Lustgassedering, per gång",
    generalPrice: 1025,
    specialistPrice: 1025,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "401",
    description: "Tanduttagning, en tand",
    generalPrice: 1280,
    specialistPrice: 1670,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "402",
    description: "Tanduttagning, när separation eller friläggning krävs, en tand",
    generalPrice: 1820,
    specialistPrice: 2380,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "403",
    description: "Tanduttagning, enkel",
    generalPrice: 510,
    specialistPrice: 660,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "404",
    description: "Kirurgiskt avlägsnande av en eller flera tänder i samma kvadrant och/eller annan vävnad",
    generalPrice: 3755,
    specialistPrice: 4800,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "405",
    description: "Dentoalveolär kirurgi vid komplicerade förhållanden",
    generalPrice: 4330,
    specialistPrice: 5520,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "406",
    description: "Tanduttagning, övertalig tand",
    generalPrice: 1280,
    specialistPrice: 1670,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "407",
    description: "Övrig kirurgi eller plastik",
    generalPrice: 2470,
    specialistPrice: 3095,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "408",
    description: "Preprotetisk friläggning med lambå, omfattande",
    generalPrice: 5010,
    specialistPrice: 6475,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "409",
    description: "Lambåoperation, ytterligare när flera lambåoperationer utförs under samma dag, per kvadrant,tilläggsåtgärd",
    generalPrice: 1550,
    specialistPrice: 2100,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "410",
    description: "Tanduttagning, ytterligare när flera tanduttagningar utförs under samma dag eller i samband med lambåoperation, tilläggsåtgärd",
    generalPrice: 945,
    specialistPrice: 1290,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "420",
    description: "Implantat, per styck",
    generalPrice: 3585,
    specialistPrice: 3585,
    dentalTechCost: null,
    materials: "Titan",
  },
  {
    code: "421",
    description: "Operation avseende käkbensförankrade implantat, ett implantat",
    generalPrice: 3755,
    specialistPrice: 4715,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "422",
    description: "Kirurgisk friläggning av ett implantat vid tvåstegsteknik",
    generalPrice: 1805,
    specialistPrice: 2225,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "423",
    description: "Operation avseende käkbensförankrade implantat, två eller tre implantat",
    generalPrice: 5455,
    specialistPrice: 6865,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "424",
    description: "Kirurgisk friläggning av två eller tre implantat vid tvåstegsteknik",
    generalPrice: 2025,
    specialistPrice: 2515,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "425",
    description: "Operation avseende käkbensförankrade implantat, fyra eller fler implantat",
    generalPrice: 7520,
    specialistPrice: 9275,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "426",
    description: "Kirurgisk friläggning av fyra eller fler implantat vid tvåstegsteknik",
    generalPrice: 2705,
    specialistPrice: 3405,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "427",
    description: "Benaugmentation med egen vävnad i en kvadrant",
    generalPrice: 4720,
    specialistPrice: 5985,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "428",
    description: "Benaugmentation med benersättningsmaterial i en kvadrant",
    generalPrice: 5680,
    specialistPrice: 6810,
    dentalTechCost: null,
    materials: "Syntetiskt benersättningsmaterial ",
  },
  {
    code: "429",
    description: "Kirurgiskt avlägsnande av implantat",
    generalPrice: 4655,
    specialistPrice: 5915,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "430",
    description: "Benaugmentation med egen vävnad i en kvadrant i samband med benaugmentation i annan kvadrant eller i implantatoperation i samma kvadrant, per kvadrant, tilläggsåtgärd",
    generalPrice: 1535,
    specialistPrice: 2085,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "431",
    description: "Benaugmentation med benersättningsmaterial i samband med benaugmentation eller implantatoperation i annan kvadrant, per kvadrant, tilläggsåtgärd",
    generalPrice: 2730,
    specialistPrice: 3280,
    dentalTechCost: null,
    materials: "Syntetiskt benersättningsmaterial ",
  },
  {
    code: "432",
    description: "Benaugmentation med benersättningsmaterial i samband med implantatinstallation, per kvadrant, tillägsåtgärd",
    generalPrice: 2030,
    specialistPrice: 2445,
    dentalTechCost: null,
    materials: "Syntetiskt benersättningsmaterial ",
  },
  {
    code: "433",
    description: "Sinuslyft utan autologt ben eller benersättningsmaterial i samband med implantatinstallation, per kvadrant, tillägsåtgärd",
    generalPrice: 1035,
    specialistPrice: 1450,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "436",
    description: "Avlägsnande av ett implantat",
    generalPrice: 805,
    specialistPrice: 1070,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "446",
    description: "Rekonstruktiv behandling med membran (GTR) eller emaljmatrixprotein, tilläggsåtgärd",
    generalPrice: 2035,
    specialistPrice: 2245,
    dentalTechCost: null,
    materials: "Regenerativt material ",
  },
  {
    code: "447",
    description: "Rekonstruktiv behandling med benersättningsmaterial, tilläggsåtgärd",
    generalPrice: 1375,
    specialistPrice: 1515,
    dentalTechCost: null,
    materials: "Regenerativt material ",
  },
  {
    code: "448",
    description: "Fritt bindvävstransplantat vid lambåoperation, tilläggsåtgärd",
    generalPrice: 755,
    specialistPrice: 1030,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "451",
    description: "Parodontalkirurgi i en kvadrant eller inom tandposition 3–3",
    generalPrice: 3910,
    specialistPrice: 5300,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "452",
    description: "Parodontalkirurgi i flera kvadranter eller omfattande parodontalkirurgi i en kvadrant eller inom tandposition 3-3",
    generalPrice: 5410,
    specialistPrice: 7285,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "453",
    description: "Kirurgisk behandling av periimplantit och i förekommande fall tänder med parodontit i en kvadrant eller inom tandposition 3-3",
    generalPrice: 4115,
    specialistPrice: 5585,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "454",
    description: "Kirurgisk behandling av periimplantit och i förekommande fall tänder med parodontit i flera kvadranter eller omfattande kirurgisk behandling i en kvadrant eller inom tandposition 3–3",
    generalPrice: 5820,
    specialistPrice: 7845,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "480",
    description: "Kontroll av koagulation, tilläggsåtgärd",
    generalPrice: 400,
    specialistPrice: 400,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "501",
    description: "Rensning och rotfyllning, en rotkanal",
    generalPrice: 4105,
    specialistPrice: 5135,
    dentalTechCost: null,
    materials: "Guttaperka och sealer",
  },
  {
    code: "502",
    description: "Rensning och rotfyllning, två rotkanaler",
    generalPrice: 4955,
    specialistPrice: 6225,
    dentalTechCost: null,
    materials: "Guttaperka och sealer",
  },
  {
    code: "503",
    description: "Rensning och rotfyllning, tre rotkanaler",
    generalPrice: 6225,
    specialistPrice: 7840,
    dentalTechCost: null,
    materials: "Guttaperka och sealer",
  },
  {
    code: "504",
    description: "Rensning och rotfyllning, fyra eller fler rotkanaler",
    generalPrice: 6790,
    specialistPrice: 8545,
    dentalTechCost: null,
    materials: "Guttaperka och sealer",
  },
  {
    code: "520",
    description: "Akut endodontisk behandling, annan behandlare",
    generalPrice: 1005,
    specialistPrice: 1310,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "521",
    description: "Akut trepanation och kavumextirpation",
    generalPrice: 885,
    specialistPrice: 1165,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "522",
    description: "Komplicerad rotkanallokalisation",
    generalPrice: 890,
    specialistPrice: 1170,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "523",
    description: "Stiftborttagning",
    generalPrice: 1300,
    specialistPrice: 1720,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "541",
    description: "Apikalkirurgisk behandling",
    generalPrice: 4410,
    specialistPrice: 5665,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "601",
    description: "Bettskena i hård akrylat i överkäken, utförd på bettfysiologisk indikation, per skena",
    generalPrice: 4370,
    specialistPrice: 5975,
    dentalTechCost: 1979.392,
    materials: null,
  },
  {
    code: "602",
    description: "Bettskena i hård akrylat i underkäken, utförd på bettfysiologisk indikation, per skena",
    generalPrice: 4370,
    specialistPrice: 5975,
    dentalTechCost: 1979.392,
    materials: null,
  },
  {
    code: "603",
    description: "Reponeringsskena, per skena",
    generalPrice: 6695,
    specialistPrice: 8150,
    dentalTechCost: 2503.68,
    materials: null,
  },
  {
    code: "604",
    description: "Mjukplastskena, laboratorieframställd, utförd på bettfysiologiska indikationer, per skena",
    generalPrice: 2780,
    specialistPrice: 3340,
    dentalTechCost: 1083.392,
    materials: null,
  },
  {
    code: "606",
    description: "Motorisk aktivering",
    generalPrice: 730,
    specialistPrice: 750,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "607",
    description: "Bettslipning för ocklusal stabilisering",
    generalPrice: 825,
    specialistPrice: 1100,
    dentalTechCost: 26.92826271744,
    materials: null,
  },
  {
    code: "650",
    description: "Motorisk aktivering, distanskontakt via videolänk",
    generalPrice: 480,
    specialistPrice: 480,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "701",
    description: "Fyllning av en yta på framtand eller hörntand",
    generalPrice: 730,
    specialistPrice: 730,
    dentalTechCost: null,
    materials: "Komposit",
  },
  {
    code: "702",
    description: "Fyllning av två ytor på framtand eller hörntand",
    generalPrice: 1160,
    specialistPrice: 1160,
    dentalTechCost: null,
    materials: "Komposit",
  },
  {
    code: "703",
    description: "Fyllning av tre eller flera ytor på framtand eller hörntand",
    generalPrice: 1420,
    specialistPrice: 1420,
    dentalTechCost: null,
    materials: "Komposit",
  },
  {
    code: "704",
    description: "Fyllning av en yta på molar eller premolar",
    generalPrice: 940,
    specialistPrice: 940,
    dentalTechCost: null,
    materials: "Komposit",
  },
  {
    code: "705",
    description: "Fyllning av två ytor på molar eller premolar",
    generalPrice: 1370,
    specialistPrice: 1370,
    dentalTechCost: null,
    materials: "Komposit",
  },
  {
    code: "706",
    description: "Fyllning av tre eller flera ytor på molar eller premolar",
    generalPrice: 1830,
    specialistPrice: 1830,
    dentalTechCost: null,
    materials: "Komposit",
  },
  {
    code: "707",
    description: "Krona i plastiskt material, klinikframställd",
    generalPrice: 2075,
    specialistPrice: 2075,
    dentalTechCost: null,
    materials: "Komposit",
  },
  {
    code: "708",
    description: "Stiftförankring i rotkanal vid fyllningsterapi, tilläggsåtgärd",
    generalPrice: 550,
    specialistPrice: 550,
    dentalTechCost: null,
    materials: "Titanstift ",
  },
  {
    code: "711",
    description: "Fyllning, utförd av tandhygienist",
    generalPrice: 505,
    specialistPrice: null,
    dentalTechCost: null,
    materials: "Komposit",
  },
  {
    code: "800",
    description: "Permanent tandstödd krona, en per käke",
    generalPrice: 6825,
    specialistPrice: 8250,
    dentalTechCost: 2033.664,
    materials: "Zirkonia/Glaskeram/Metallkeramik",
  },
  {
    code: "801",
    description: "Permanent tandstödd krona, flera i samma käke",
    generalPrice: 5275,
    specialistPrice: 6395,
    dentalTechCost: 2033.664,
    materials: "Zirkonia / Metallkeramik",
  },
  {
    code: "802",
    description: "Laboratorieframställd pelare med intraradikulärt stift",
    generalPrice: 3880,
    specialistPrice: 4720,
    dentalTechCost: 1091.584,
    materials: "Gjutmetall",
  },
  {
    code: "803",
    description: "Klinikframställd pelare med intraradikulärt stift",
    generalPrice: 1810,
    specialistPrice: 2295,
    dentalTechCost: null,
    materials: "Fiberförstärkt stift, titanstift ",
  },
  {
    code: "804",
    description: "Hängande led vid tandstödd protetik, per led",
    generalPrice: 2815,
    specialistPrice: 3100,
    dentalTechCost: 2010.112,
    materials: "Fullzirkonia, Metallkeramik ",
  },
  {
    code: "805",
    description: "Laboratorieframställt emaljretinerat brostöd, per stöd",
    generalPrice: 2165,
    specialistPrice: 2580,
    dentalTechCost: 722.944,
    materials: "Metall alt Zirkonia",
  },
  {
    code: "806",
    description: "Radikulärförankring vid avtagbar protes",
    generalPrice: 4105,
    specialistPrice: 4945,
    dentalTechCost: 1367.74817402084,
    materials: "Gjutmetall, förankringselement",
  },
  {
    code: "807",
    description: "Semipermanent tandstödd krona, brostöd eller hängande led, per led",
    generalPrice: 3160,
    specialistPrice: 3650,
    dentalTechCost: 1522.688,
    materials: "Gjut/ fräst metall + plast/ porslin. 3D-printad alt fräst hybrid-/helkeramik",
  },
  {
    code: "808",
    description: "Innerkrona för teleskop- och konuskonstruktioner",
    generalPrice: 4020,
    specialistPrice: 4855,
    dentalTechCost: 1522.688,
    materials: "Metall ",
  },
  {
    code: "809",
    description: "Långtidstemporär tandstödd laboratorieframställd krona, brostöd eller hängande led, per led",
    generalPrice: 1350,
    specialistPrice: 1560,
    dentalTechCost: 592.896,
    materials: "Akrylat fräst/ CAD/3-D",
  },
  {
    code: "811",
    description: "Cementering av lossnad tandstödd eller implantatstödd protetisk konstruktion, per stöd",
    generalPrice: 635,
    specialistPrice: 845,
    dentalTechCost: null,
    materials: "Parapulpala titanstift ",
  },
  {
    code: "812",
    description: "Reparation av krona eller bro, utan tandteknisk insats",
    generalPrice: 1625,
    specialistPrice: 2185,
    dentalTechCost: null,
    materials: "Komposit",
  },
  {
    code: "813",
    description: "Broreparation med tandteknisk insats",
    generalPrice: 5470,
    specialistPrice: 6865,
    dentalTechCost: 1077.1273109664,
    materials: "Gjut/ fräst metall + porslin",
  },
  {
    code: "814",
    description: "Broreparation med tandteknisk insats, omfattande",
    generalPrice: 9575,
    specialistPrice: 11805,
    dentalTechCost: 2050.01649506509,
    materials: "Metall + ev porslin",
  },
  {
    code: "815",
    description: "Sadelkrona",
    generalPrice: 6135,
    specialistPrice: 7390,
    dentalTechCost: 2033.664,
    materials: "Metallkeramik, Fullzirkonia ",
  },
  {
    code: "820",
    description: "Skena med tandersättning för temporärt bruk",
    generalPrice: 1550,
    specialistPrice: 1760,
    dentalTechCost: 958.464,
    materials: "Laboratorieframställd plastskena, komposit",
  },
  {
    code: "822",
    description: "Partiell protes för temporärt bruk, en till tre tänder",
    generalPrice: 5000,
    specialistPrice: 5835,
    dentalTechCost: 2334.72,
    materials: "Akrylat, klamrar (rostfria, 2 st), proteständer",
  },
  {
    code: "823",
    description: "Partiell protes för temporärt bruk, fyra eller fler tänder",
    generalPrice: 6785,
    specialistPrice: 7900,
    dentalTechCost: 3272.704,
    materials: "Akrylat, klamrar (rostfria, 2 st), proteständer",
  },
  {
    code: "824",
    description: "Partiell protes med gjutet skelett, klammerförankrad",
    generalPrice: 13620,
    specialistPrice: 15575,
    dentalTechCost: 5373.952,
    materials: "Akrylat, CoCr-skelett inkl passiva klamrar, dragna klamrar (2 st), proteständer (Clasp 50%)",
  },
  {
    code: "825",
    description: "Komplicerad partiell protes med metallskelett som förankras med stöd av urtagskrona, innerkrona eller attachments",
    generalPrice: 15250,
    specialistPrice: 18510,
    dentalTechCost: 6571.008,
    materials: "Akrylat, CoCr-skelett inkl passiva klamrar (komplicerat), dragna klamrar (2 st), proteständer,( Clasp 50%)",
  },
  {
    code: "826",
    description: "Attachments, per styck",
    generalPrice: 185,
    specialistPrice: 185,
    dentalTechCost: null,
    materials: "Plast (matris/patris) ",
  },
  {
    code: "827",
    description: "Hel underkäksprotes",
    generalPrice: 12510,
    specialistPrice: 15455,
    dentalTechCost: 4981.76,
    materials: "Akrylat, proteständer ",
  },
  {
    code: "828",
    description: "Hel överkäksprotes",
    generalPrice: 12510,
    specialistPrice: 15455,
    dentalTechCost: 4981.76,
    materials: "Akrylat, proteständer ",
  },
  {
    code: "829",
    description: "Immediatprotes, hel käke",
    generalPrice: 9270,
    specialistPrice: 10790,
    dentalTechCost: 4516.864,
    materials: "Akrylat, proteständer ",
  },
  {
    code: "831",
    description: "Justering av avtagbar protes",
    generalPrice: 415,
    specialistPrice: 555,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "832",
    description: "Lagning av protes eller tillsättning av protestand",
    generalPrice: 1990,
    specialistPrice: 2270,
    dentalTechCost: 1074.176,
    materials: "Protestand, akrylat",
  },
  {
    code: "833",
    description: "Rebasering av protes där avtryck krävs",
    generalPrice: 3455,
    specialistPrice: 4085,
    dentalTechCost: 1306.624,
    materials: "Akrylat",
  },
  {
    code: "834",
    description: "Lagning av protes där avtryck krävs",
    generalPrice: 2630,
    specialistPrice: 3050,
    dentalTechCost: 1277.952,
    materials: "Akrylat, klammer ",
  },
  {
    code: "835",
    description: "Rebasering och lagning av protes",
    generalPrice: 3975,
    specialistPrice: 4670,
    dentalTechCost: 1600.512,
    materials: "Akrylat, klammer ",
  },
  {
    code: "836",
    description: "Komplicerad lagning av protes",
    generalPrice: 4150,
    specialistPrice: 4845,
    dentalTechCost: 1907.712,
    materials: "Akrylat, (dragen)klammer, proteständer, (Clasp 50%)",
  },
  {
    code: "837",
    description: "Komplicerad lagning av protes där uppvaxning och gjutning av ny del utförs vilken svetsas till befintlig protes",
    generalPrice: 9195,
    specialistPrice: 10395,
    dentalTechCost: 3584.0,
    materials: "Akrylat, Gjut/ fräst metall, klammer, proteständer, (Clasp 50%)",
  },
  {
    code: "839",
    description: "Inmontering av förankringselement, per käke",
    generalPrice: 3595,
    specialistPrice: 4290,
    dentalTechCost: 1234.64270267762,
    materials: "Akrylat ",
  },
  {
    code: "845",
    description: "Ocklusionskorrigerande bettslipning",
    generalPrice: 2255,
    specialistPrice: 2780,
    dentalTechCost: 498.7392,
    materials: "Parslipade studiemodeller. I förekommande fall frästa eller 3-D printade studiemodeller. ",
  },
  {
    code: "846",
    description: "Skena, hel eller cementerad i sektioner, för vertikal platsberedning eller bettstabilisering",
    generalPrice: 4685,
    specialistPrice: 5660,
    dentalTechCost: 1480.704,
    materials: "CoCr ",
  },
  {
    code: "847",
    description: "Klammerplåt",
    generalPrice: 5650,
    specialistPrice: 6625,
    dentalTechCost: 2430.976,
    materials: "Akrylat, klammer ",
  },
  {
    code: "848",
    description: "Betthöjning eller uppbyggnad för ocklusal stabilisering med fyllningsmaterial, per tandposition",
    generalPrice: 600,
    specialistPrice: 810,
    dentalTechCost: null,
    materials: "Komposit ",
  },
  {
    code: "850",
    description: "Implantatstödd krona, en per käke",
    generalPrice: 10355,
    specialistPrice: 12035,
    dentalTechCost: 3899.392,
    materials: "Metallkeramik eller fullzirkonia på titanbas inkl fästskruv, komposit i skruvhål",
  },
  {
    code: "852",
    description: "Implantatstödd krona, flera i samma käke",
    generalPrice: 8230,
    specialistPrice: 9480,
    dentalTechCost: 3640.32,
    materials: "Metallkeramik eller fullzirkonia på titanbas inkl fästskruv, komposit i skruvhål",
  },
  {
    code: "853",
    description: "Hängande led vid implantatstödd bro",
    generalPrice: 2845,
    specialistPrice: 3125,
    dentalTechCost: 2084.864,
    materials: "Metallkeramik eller fullzirkonia ",
  },
  {
    code: "854",
    description: "Semipermanent implantatstödd krona, brostöd eller hängande led, per led",
    generalPrice: 3550,
    specialistPrice: 3970,
    dentalTechCost: 2148.352,
    materials: "Gjut/ fräst metall inkl svetsning, fasadmaterial, 3D-printad alt fräst hybrid-/helkeramik, komposit i skruvhål",
  },
  {
    code: "855",
    description: "Fästskruv/broskruv och cylinder vid semipermanent krona på implantat, per implantat",
    generalPrice: 620,
    specialistPrice: 620,
    dentalTechCost: null,
    materials: "Titan",
  },
  {
    code: "856",
    description: "Långtidstemporär laboratorieframställd implantatstödd krona, brostöd eller hängande led, per led",
    generalPrice: 2035,
    specialistPrice: 2310,
    dentalTechCost: 1074.176,
    materials: "Akrylat fräst/ CAD/3-D",
  },
  {
    code: "857",
    description: "Fästskruv/broskruv och cylinder vid långtidstemporär laboratorieframställd krona på implantat, per implantat",
    generalPrice: 620,
    specialistPrice: 620,
    dentalTechCost: null,
    materials: "Titan",
  },
  {
    code: "858",
    description: "Distans inkl distansskruv, per styck",
    generalPrice: 1580,
    specialistPrice: 1580,
    dentalTechCost: null,
    materials: "Titandistans inkl centrumskruv ",
  },
  {
    code: "859",
    description: "Integrerad distans/kopplingskomponent vid separat implantatstödd krona, per styck, tilläggsåtgärd",
    generalPrice: 1005,
    specialistPrice: 1005,
    dentalTechCost: null,
    materials: "Titan",
  },
  {
    code: "861",
    description: "Implantatstödd bro i överkäke på fyra implantat",
    generalPrice: 36530,
    specialistPrice: 40735,
    dentalTechCost: 22397.952,
    materials: "Metallskelett inkl fästskruvar och proteständer eller, fullzirkonia med eller utan metallbas inklusive fästskruvar",
  },
  {
    code: "862",
    description: "Implantatstödd bro i överkäke på fem implantat",
    generalPrice: 37845,
    specialistPrice: 42050,
    dentalTechCost: 23653.376,
    materials: "Metallskelett inkl fästskruvar och proteständer eller, fullzirkonia med eller utan metallbas inklusive fästskruvar",
  },
  {
    code: "863",
    description: "Implantatstödd bro i överkäke på sex eller fler implantat",
    generalPrice: 39160,
    specialistPrice: 43370,
    dentalTechCost: 24909.824,
    materials: "Metallskelett inkl fästskruvar och proteständer eller, fullzirkonia med eller utan metallbas inklusive fästskruvar",
  },
  {
    code: "865",
    description: "Implantatstödd bro i underkäke på fyra implantat eller fler implantat",
    generalPrice: 35225,
    specialistPrice: 39010,
    dentalTechCost: 22397.952,
    materials: "Metallskelett inkl fästskruvar och proteständer eller, fullzirkonia med eller utan metallbas inklusive fästskruvar",
  },
  {
    code: "871",
    description: "Implantatstödd täckprotes i överkäke på två implantat, eller implantatstödd täckprotes i underkäke p",
    generalPrice: 21120,
    specialistPrice: 24120,
    dentalTechCost: 7024.64,
    materials: "Akrylat, proteständer",
  },
  {
    code: "872",
    description: "Implantatstödd täckprotes i överkäke på tre implantat",
    generalPrice: 23175,
    specialistPrice: 26175,
    dentalTechCost: 7024.64,
    materials: "Akrylat, proteständer",
  },
  {
    code: "873",
    description: "Implantatstödd täckprotes i överkäke på fyra implantat eller fler",
    generalPrice: 25235,
    specialistPrice: 28230,
    dentalTechCost: 7024.64,
    materials: "Akrylat, proteständer",
  },
  {
    code: "874",
    description: "Tillägg för alveolarbar på två implantat",
    generalPrice: 5330,
    specialistPrice: 5750,
    dentalTechCost: 4034.56,
    materials: "Fästskruv (titan), knäppen (guld), titan (gjutet eller fräst) ",
  },
  {
    code: "875",
    description: "Tillägg för alveolarbar på tre implantat",
    generalPrice: 6975,
    specialistPrice: 7395,
    dentalTechCost: 5677.056,
    materials: "Fästskruv (titan), knäppen (guld), titan (gjutet eller fräst) ",
  },
  {
    code: "876",
    description: "Tillägg för alveolarbar på fyra implantat",
    generalPrice: 8500,
    specialistPrice: 8920,
    dentalTechCost: 7195.648,
    materials: "Fästskruv (titan), knäppen (guld), titan (gjutet eller fräst) ",
  },
  {
    code: "877",
    description: "Implantatstödd täckprotes, exklusive implantat, implantat-komponeter och förankringselement",
    generalPrice: 17105,
    specialistPrice: 20105,
    dentalTechCost: 7024.64,
    materials: "Akrylat, proteständer",
  },
  {
    code: "878",
    description: "Förankringselement täckprotes, tillägg, per styck",
    generalPrice: 330,
    specialistPrice: 330,
    dentalTechCost: null,
    materials: "Knäppen ",
  },
  {
    code: "881",
    description: "Reparation av fast implantatstödd konstruktion, mindre omfattande",
    generalPrice: 1220,
    specialistPrice: 1640,
    dentalTechCost: null,
    materials: "Komposit ",
  },
  {
    code: "883",
    description: "Reparation/ombyggnad av fast implantatstödd konstruktion med tandteknisk insats",
    generalPrice: 2515,
    specialistPrice: 2865,
    dentalTechCost: 1388.544,
    materials: "Erf material, Komposit ",
  },
  {
    code: "884",
    description: "Reparation/ombyggnad av implantatstödd bro där omfattande tandteknisk insats krävs",
    generalPrice: 9815,
    specialistPrice: 10720,
    dentalTechCost: 6915.072,
    materials: "Erf material, Komposit ",
  },
  {
    code: "888",
    description: "Fästskruv/broskruv, per styck",
    generalPrice: 205,
    specialistPrice: 205,
    dentalTechCost: null,
    materials: "Titan, komposit",
  },
  {
    code: "889",
    description: "Distansskruv, per styck",
    generalPrice: 435,
    specialistPrice: 435,
    dentalTechCost: null,
    materials: "Titan",
  },
  {
    code: "892",
    description: "Läkdistans, per styck",
    generalPrice: 385,
    specialistPrice: 385,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "893",
    description: "Avmontering av implantatstödda konstruktioner på sammanlagt ett till tre implantat",
    generalPrice: 1180,
    specialistPrice: 1595,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "894",
    description: "Återmontering av implantatstödda konstruktioner på sammanlagt ett till tre implantat",
    generalPrice: 1235,
    specialistPrice: 1655,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "895",
    description: "Avmontering av implantatstödda konstruktioner på sammanlagt fyra eller fler implantat",
    generalPrice: 1555,
    specialistPrice: 2110,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "896",
    description: "Återmontering av implantatstödda konstruktioner på sammanlagt fyra eller fler implantat",
    generalPrice: 1680,
    specialistPrice: 2235,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "897",
    description: "Åtgärdande av tekniska implantatkomplikationer",
    generalPrice: 2835,
    specialistPrice: 4135,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "900",
    description: "Tandreglering, en käke, aktiv behandling högst 6 månader",
    generalPrice: 11195,
    specialistPrice: 14580,
    dentalTechCost: 470.910799298598,
    materials: null,
  },
  {
    code: "901",
    description: "Tandreglering, en käke, aktiv behandling högst 1 år",
    generalPrice: 16800,
    specialistPrice: 21885,
    dentalTechCost: 941.821598597197,
    materials: null,
  },
  {
    code: "902",
    description: "Tandreglering, en käke, aktiv behandling 1 år till 1,5 år",
    generalPrice: 20940,
    specialistPrice: 27470,
    dentalTechCost: 941.821598597197,
    materials: null,
  },
  {
    code: "903",
    description: "Tandreglering, en käke, aktiv behandling 1,5 år till 2 år",
    generalPrice: 24700,
    specialistPrice: 32535,
    dentalTechCost: 941.821598597197,
    materials: null,
  },
  {
    code: "904",
    description: "Tandreglering, en käke, aktiv behandling mer än 2 år",
    generalPrice: 30645,
    specialistPrice: 40540,
    dentalTechCost: 941.821598597197,
    materials: null,
  },
  {
    code: "905",
    description: "Tandreglering, två käkar, aktiv behandling högst 1 år",
    generalPrice: 23620,
    specialistPrice: 30425,
    dentalTechCost: 1545.40738729915,
    materials: null,
  },
  {
    code: "906",
    description: "Tandreglering, två käkar, aktiv behandling 1 år till 1,5 år",
    generalPrice: 27760,
    specialistPrice: 36010,
    dentalTechCost: 1545.40738729915,
    materials: null,
  },
  {
    code: "907",
    description: "Tandreglering, två käkar, aktiv behandling 1,5 år till 2 år",
    generalPrice: 31900,
    specialistPrice: 41590,
    dentalTechCost: 1545.40738729915,
    materials: null,
  },
  {
    code: "908",
    description: "Tandreglering, två käkar, aktiv behandling i mer än 2 år",
    generalPrice: 38475,
    specialistPrice: 50435,
    dentalTechCost: 1545.40738729915,
    materials: null,
  },
  {
    code: "921",
    description: "Utbytesåtgärd. Krona istället för ersättningsberättigande fyllning, fram- eller hörntand",
    generalPrice: 1420,
    specialistPrice: 1420,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "922",
    description: "Utbytesåtgärd. Krona istället för ersättningsberättigande fyllning, molar eller premolar",
    generalPrice: 1830,
    specialistPrice: 1830,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "923",
    description: "Utbytesåtgärd. Fasad i stället för ersättningsberättigande fyllning, tandposition 1–3",
    generalPrice: 1420,
    specialistPrice: 1420,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "924",
    description: "Utbytesåtgärd. Fasad i stället för ersättningsberättigande fyllning, tandposition 4–5",
    generalPrice: 1830,
    specialistPrice: 1830,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "926",
    description: "Utbytesåtgärd. Implantatbehandling i entandslucka istället för ersättningsberättigande tandstödd bro, protetisk del/implantatstödd krona",
    generalPrice: 8090,
    specialistPrice: 9495,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "929",
    description: "Utbytesåtgärd. Implantatbehandling i entandslucka istället för ersättningsberättigande tandstödd bro när åtgärd 800 eller 801 har utförts inom två år på en av stödtänderna som utbytet beräknas på, protetisk del/implantatstödd krona",
    generalPrice: 5275,
    specialistPrice: 6395,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "940",
    description: "Utbytesåtgärd. Ortodontisk slutning av entandslucka i stället för ersättningsberättigande tandstödd bro",
    generalPrice: 13365,
    specialistPrice: 15890,
    dentalTechCost: null,
    materials: null,
  },
  {
    code: "941",
    description: "Utbytesåtgärd. Ortodontisk slutning av entandslucka istället för ersättningsberättigande tandstödd bro när åtgärd 800 eller 801 har utförts inom två år på en av stödtänderna som utbytet beräknas på",
    generalPrice: 8090,
    specialistPrice: 9495,
    dentalTechCost: null,
    materials: null,
  },
];

// Category mapping for Swedish dental codes
export const treatmentCategories = {
  '1': 'Undersöking och diagnostik (Examination & Diagnosis)',
  '2': 'Behandling av karies (Caries Treatment)',
  '3': 'Endodonti (Root Canal Treatment)',
  '4': 'Parodontologi (Periodontal Treatment)',
  '5': 'Kirurgi (Dental Surgery)',
  '6': 'Tandprotes (Prosthetics)',
  '7': 'Ortodonti (Orthodontics)',
  '8': 'Övrig tandvård (Other Dental Care)',
  '9': 'Tandimplantat (Dental Implants)',
} as const;

export function getCategoryForCode(code: string): string {
  const firstDigit = code[0];
  return treatmentCategories[firstDigit as keyof typeof treatmentCategories] || 'Unknown';
}

export function getPriceRange(codes: string[]): { min: number; max: number } | null {
  const prices = dentalReferencePrices
    .filter(p => codes.includes(p.code))
    .flatMap(p => [p.generalPrice, p.specialistPrice].filter((x): x is number => x !== null));
  
  if (prices.length === 0) return null;
  return {
    min: Math.min(...prices),
    max: Math.max(...prices),
  };
}
