import type { Clinic, Offer, PriceData } from "@/types";

export const CLINICS: Clinic[] = [
  {
    id: "citysmile",
    initials: "CS",
    name: "Citysmile",
    address: "Hornsgatan 42, Södermalm, Stockholm",
    area: "Södermalm, Stockholm",
    rating: 4.9,
    ratingCount: 127,
    tags: ["Akuttandvård", "Allmäntandvård", "Estetisk"],
    svarstid: "2 tim",
    available: true,
    availText: "Lediga tider imorgon",
    about: "Citysmile grundades 2018 och har snabbt blivit en av Södermalms mest populära tandvårdskliniker. Vi fokuserar på modern, skonsam tandvård med fokus på patientens upplevelse. Kliniken är utrustad med digital röntgen och intraorala kameror.",
    treatments: [
      "Undersökning",
      "Akuttandvård",
      "Rotfyllning",
      "Tandblekning",
      "Estetisk tandvård",
      "Tandkronor",
      "Implantat",
    ],
    hours: {
      "Mån–Tor": "08:00–18:00",
      Fre: "08:00–16:00",
      Lör: "09:00–14:00",
      Sön: "Stängt",
    },
    responseRate: "98%",
    avgPrice: "Under snitt",
    patients: "2 400+",
  },
  {
    id: "nordtand",
    initials: "NT",
    name: "Nordtand",
    address: "Odengatan 15, Vasastan, Stockholm",
    area: "Vasastan, Stockholm",
    rating: 4.7,
    ratingCount: 89,
    tags: ["Allmäntandvård", "Barntandvård", "Protetik"],
    svarstid: "6 tim",
    available: true,
    availText: "Lediga tider om 3 dagar",
    about: "Nordtand är en familjevänlig klinik i hjärtat av Vasastan. Sedan 2012 har vi tagit emot patienter i alla åldrar med fokus på trygg och noggrann tandvård. Vi erbjuder allt från basundersökningar till avancerad protetik.",
    treatments: [
      "Undersökning",
      "Barntandvård",
      "Protetik",
      "Tandkronor",
      "Broar",
      "Rotfyllning",
      "Fyllningar",
    ],
    hours: { "Mån–Fre": "08:00–17:00", "Lör–Sön": "Stängt" },
    responseRate: "92%",
    avgPrice: "Över snitt",
    patients: "1 800+",
  },
  {
    id: "ostermalm",
    initials: "ÖT",
    name: "Östermalms Tandvård",
    address: "Karlavägen 28, Östermalm, Stockholm",
    area: "Östermalm, Stockholm",
    rating: 4.8,
    ratingCount: 204,
    tags: ["Estetisk", "Implantat", "Allmäntandvård"],
    svarstid: "45 min",
    available: true,
    availText: "Lediga tider om 1 dag",
    about: "Östermalms Tandvård har sedan 2009 erbjudit tandvård i toppklass. Kliniken specialiserar sig på estetisk tandvård och implantat, med ett team av specialister som samarbetar för bästa möjliga resultat.",
    treatments: [
      "Estetisk tandvård",
      "Implantat",
      "Tandblekning",
      "Skalfasader",
      "Invisalign",
      "Undersökning",
      "Tandkronor",
    ],
    hours: {
      "Mån–Tor": "07:30–18:30",
      Fre: "07:30–15:00",
      Lör: "10:00–14:00",
      Sön: "Stängt",
    },
    responseRate: "99%",
    avgPrice: "Runt snitt",
    patients: "3 100+",
  },
  {
    id: "goteborg-city",
    initials: "GC",
    name: "Göteborg City Dental",
    address: "Kungsgatan 8, Centrum, Göteborg",
    area: "Centrum, Göteborg",
    rating: 4.6,
    ratingCount: 156,
    tags: ["Akuttandvård", "Allmäntandvård", "Rotbehandling"],
    svarstid: "4 tim",
    available: true,
    availText: "Lediga tider imorgon",
    about: "Göteborg City Dental ligger centralt vid Kungsgatan och har betjänat Göteborgs invånare sedan 2015. Vi är kända för snabb och professionell akuttandvård med korta väntetider.",
    treatments: [
      "Undersökning",
      "Akuttandvård",
      "Rotfyllning",
      "Fyllningar",
      "Tandkronor",
      "Tandextraktion",
    ],
    hours: {
      "Mån–Fre": "07:00–19:00",
      Lör: "09:00–15:00",
      Sön: "Akuttid via telefon",
    },
    responseRate: "95%",
    avgPrice: "Under snitt",
    patients: "2 900+",
  },
  {
    id: "malmo-smile",
    initials: "MS",
    name: "Malmö Smile",
    address: "Stortorget 3, Centrum, Malmö",
    area: "Centrum, Malmö",
    rating: 4.9,
    ratingCount: 78,
    tags: ["Estetisk", "Tandblekning", "Allmäntandvård"],
    svarstid: "1 tim",
    available: true,
    availText: "Lediga tider idag",
    about: "Malmö Smile är Malmös nyaste tandvårdsklinik, öppnad 2023 med toppmodern utrustning. Vi kombinerar skandinavisk design med avancerad tandvårdsteknik.",
    treatments: [
      "Estetisk tandvård",
      "Tandblekning",
      "Skalfasader",
      "Undersökning",
      "Invisalign",
      "Kompositfyllningar",
    ],
    hours: {
      "Mån–Fre": "08:00–17:00",
      Lör: "10:00–14:00",
      Sön: "Stängt",
    },
    responseRate: "97%",
    avgPrice: "Runt snitt",
    patients: "650+",
  },
  {
    id: "uppsala-tandklinik",
    initials: "UT",
    name: "Uppsala Tandklinik",
    address: "Dragarbrunnsgatan 52, Uppsala",
    area: "Centrum, Uppsala",
    rating: 4.7,
    ratingCount: 112,
    tags: ["Allmäntandvård", "Parodontologi", "Barntandvård"],
    svarstid: "3 tim",
    available: false,
    availText: "Nästa lediga: måndag",
    about: "Uppsala Tandklinik har funnits sedan 2006 och är en av Uppsalas mest etablerade privata tandvårdskliniker. Vi har särskild kompetens inom parodontologi.",
    treatments: [
      "Undersökning",
      "Parodontologi",
      "Barntandvård",
      "Tandsten",
      "Rotfyllning",
      "Fyllningar",
      "Tandkronor",
    ],
    hours: {
      "Mån–Tor": "08:00–17:30",
      Fre: "08:00–15:00",
      "Lör–Sön": "Stängt",
    },
    responseRate: "90%",
    avgPrice: "Under snitt",
    patients: "2 200+",
  },
];

export const OFFERS: Offer[] = [
  {
    id: 1,
    clinic: "Citysmile",
    area: "Södermalm",
    distance: "0.8 km",
    price: 3200,
    wait: "Imorgon",
    responseTime: "2 tim",
    rating: 4.9,
    ratingCount: 127,
    availType: "calendar",
    badge: "lowest",
    scope:
      "Undersökning, röntgen (2 bilder), akut bedömning, behandlingsplan.",
    validUntil: "28 mars 2026",
  },
  {
    id: 2,
    clinic: "Nordtand",
    area: "Vasastan",
    distance: "2.1 km",
    price: 4100,
    wait: "Om 3 dagar",
    responseTime: "6 tim",
    rating: 4.7,
    ratingCount: 89,
    availType: "clinic",
    badge: null,
    scope:
      "Undersökning, panoramaröntgen, bedömning, akutbehandling vid behov.",
    validUntil: "31 mars 2026",
  },
  {
    id: 3,
    clinic: "Östermalms Tandvård",
    area: "Östermalm",
    distance: "4.5 km",
    price: 3800,
    wait: "Om 1 dag",
    responseTime: "45 min",
    rating: 4.8,
    ratingCount: 204,
    availType: "calendar",
    badge: "fastest",
    scope:
      "Undersökning, röntgen, akut bedömning, eventuell provisorisk åtgärd.",
    validUntil: "30 mars 2026",
  },
];

export const REF_MEAN = 3600;

export const PRICE_DATA: PriceData[] = [
  {
    avg: 1460,
    low: 800,
    high: 2200,
    refPrice: 1520,
    context: "Vanligaste första besöket. Inkluderar ofta 2 röntgenbilder.",
  },
  {
    avg: 4380,
    low: 2500,
    high: 7000,
    refPrice: 3850,
    context: "Varierar beroende på tand och antal rotkanaler.",
  },
  {
    avg: 7080,
    low: 4500,
    high: 11000,
    refPrice: 7250,
    context: "Materialet (porslin, zirkonia) påverkar priset mest.",
  },
  {
    avg: 1200,
    low: 500,
    high: 2000,
    refPrice: 1350,
    context: "Helg- och kvällstider kan ha 50% påslag.",
  },
  {
    avg: 3200,
    low: 1500,
    high: 5500,
    refPrice: 2950,
    context: "Klinikblekning. Hemblekning är ofta billigare.",
  },
];

export const PRICE_INCLUDES: string[][] = [
  ["Klinisk undersökning", "2 röntgenbilder", "Behandlingsplan"],
  ["Bedövning", "Rotkanalsbehandling", "Temporär fyllning", "Kontrollbesök"],
  ["Avtryck/skanning", "Krona (porslin eller zirkonia)", "Cementering"],
  ["Akut bedömning", "Ev. röntgen", "Smärtlindring"],
  ["Konsultation", "Klinikblekning (1–2 sessioner)", "Uppföljning"],
];

/** Per-clinic reported prices per treatment (from Tandpriskollen) */
export const CLINIC_PRICES: { clinic: string; prices: number[] }[] = [
  { clinic: "Citysmile",            prices: [1350, 3900, 6200, 950, 2800] },
  { clinic: "Nordtand",             prices: [1600, 4800, 7500, 1400, 3600] },
  { clinic: "Östermalms Tandvård",  prices: [1480, 4200, 7800, 1250, 3100] },
  { clinic: "Göteborg City Dental", prices: [1280, 3700, 6500, 1050, 2600] },
  { clinic: "Malmö Smile",          prices: [1500, 4500, 7200, 1100, 3400] },
  { clinic: "Uppsala Tandklinik",   prices: [1320, 4100, 6800, 980, 2900] },
];

export const PRICE_LABELS = [
  "Undersökning + röntgen",
  "Rotfyllning",
  "Permanent krona",
  "Akutbesök",
  "Tandblekning",
];
